services:
  backend:
    container_name: backend
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NEO4J_DB_HOST=neo4j_db
    depends_on:
      neo4j_db:
        condition: service_healthy
    networks:
      - app-network

  neo4j_db:
    container_name: neo4j_db
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - REDIS_URL=redis://peaceful_lichterman:6379
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider localhost:7474 || exit 1',
        ]
    volumes:
      - ./neo4j-data:/data
    ports:
      - '7474:7474'
      - '7687:7687'
    networks:
      - app-network

volumes:
  neo4j-data:

networks:
  app-network:
    driver: bridge
